# application-example.properties

spring.application.name=cadastrocliente

# Porta da aplica\u00E7\u00E3o

server.port=8081

app.url=${"http://34.39.187.204":http://localhost:8081}

# DATABASE (PostgreSQL)

# Defina via vari\u00E1vel de ambiente ou substitua aqui para uso local

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clientedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:senha do banco de dados}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Mostrar SQL no console (desabilitar em produ\u00E7\u00E3o)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# MESSAGES
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# CONFIG SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/v3/api-docs

#SEND EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:email para enviar a notifica\u00E7\u00E3o}
spring.mail.password=${SPRING_MAIL_PASSWORD:senha de app do gmail}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:3000}

#ACTUATOR HEALTH
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.mail.enabled=false
