spring.application.name=cadastrocliente

#PORTA DA APLICACAOO
server.port = 8081

# CONFIGURACAO DO BANCO
spring.datasource.url=jdbc:postgresql://localhost:5432/clientedb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# MOSTRAR SQL NO CONSOLE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
