# application-example.properties

spring.application.name=NOME_DA_APLICA\u00C7\u00C3O

# Porta da aplica\u00E7\u00E3o

server.port=PORTA_DA_APLICA\u00C7\u00C3O

app.url=http://localhost:8080

# DATABASE (PostgreSQL)

# Defina via vari\u00E1vel de ambiente ou substitua aqui para uso local

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/NOME_DO_BANCO}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:USUARIO}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Mostrar SQL no console (desabilitar em produ\u00E7\u00E3o)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MESSAGES
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# CONFIG SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/v3/api-docs

#SEND EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=EMAIL_VERIFICA\u00C7\u00C3O
spring.mail.password=SENHA_EMAIL

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.cors.allowed-origin=http://localhost:PORTA_DA_APLICA\u00C7\u00C3O_FRONTEND
