apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastrocliente
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadastrocliente
  template:
    metadata:
      labels:
        app: cadastrocliente
    spec:
      containers:
        - name: cadastrocliente
          image: southamerica-east1-docker.pkg.dev/viratech-1010-508115/cadastrocliente-api-repo/cadastrocliente-app:v1
          ports:
            - containerPort: 8081

          readinessProbe:
            httpGet:
              path: /users # Rota da API que responde com status 200 OK
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/clientedb

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password

            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"

            - name: SPRING_MAIL_PORT
              value: "587"

            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-url

            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mail-username

            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mail-password

            - name: SERVER_PORT
              value: "8081"

            - name: APP_CORS_ALLOWED_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: cors-allowed-origin

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z postgres 5432; do echo waiting for db; sleep 2; done;' ]