name: CI/CD Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build do projeto
        run: mvn clean package -DskipTests

#      - name: Login no Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Build da imagem
#        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cadastrocliente:latest .
#
#      - name: Push da imagem
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/cadastrocliente:latest

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configurar docker para Artifact Registry
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev
      - name: Build da imagem
        run: |
          docker build -t southamerica-east1-docker.pkg.dev/viratech-1010/cadastrocliente-repo/app:${{ github.sha }} .

      - name: Push da imagem
        run: |
          docker push southamerica-east1-docker.pkg.dev/viratech-1010/cadastrocliente-repo/app:${{ github.sha }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: viratech-cluster-cadastrocliente
          location: southamerica-east1

      - name: Aplicar PVC primeiro
        run: kubectl apply -f k8s/postgres-pvc.yaml

      - name: Aguardar PVC
        run: kubectl wait --for=condition=Bound pvc/postgres-pvc --timeout=60s

      - name: Aplicar manifestos
        run: kubectl apply -f k8s/

      - name: Atualizar imagem
        run: |
          kubectl set image deployment/cadastrocliente \
          cadastrocliente=southamerica-east1-docker.pkg.dev/viratech-1010/cadastrocliente-repo/app:${{ github.sha }}

      - name: Aguardar rollout
        run: kubectl rollout status deployment/cadastrocliente
